---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-processor
spec:
  minReadySeconds: 60
  replicas: 1
  selector:
    matchLabels:
      app: order-processor
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: order-processor
    spec:
      containers:
      - name: order-processor
        image: sustainabilitylab.azurecr.io/order-processor:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        - containerPort: 8443
        envFrom:
        - configMapRef:
            name: order-processor-env
      terminationGracePeriodSeconds: 180