bases:
- ../../../webhooks-api  

patchesStrategicMerge:
- deployment.yml

namespace: app-eshop

configMapGenerator:
- name: webhooks-api-env
  behavior: merge
  literals:
    - Identity__Url=http://identity-api:8080
