bases:
- ../../../webhooksclient

patchesStrategicMerge:
- deployment.yml

namespace: app-eshop

configMapGenerator:
- name: webhooksclient-env
  behavior: merge
  literals:
    - IdentityUrl=http://identity-api:8080
    
