---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: basket-api
spec:
  minReadySeconds: 60
  replicas: 1
  selector:
    matchLabels:
      app: basket-api
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: basket-api
    spec:
      containers:
      - name: basket-api
        image: sustainabilitylab.azurecr.io/basket-api:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        - containerPort: 8443
        envFrom:
        - configMapRef:
            name: basket-api-env
      terminationGracePeriodSeconds: 180