bases:
- ../../../ordering-api  

patchesStrategicMerge:
- deployment.yml

namespace: app-eshop

configMapGenerator:
- name: ordering-api-env
  behavior: merge
  literals:
    - Identity__Url=http://identity-api:8080

