apiVersion: v1
kind: Secret
metadata:
  name: basket-api-cert
type: Opaque
data:
  tls.pfx: |
    MIACAQMwgAYJKoZIhvcNAQcBoIAkgASCA+gwgDCABgkqhkiG9w0BBwGggCSABIID6DCCChswggoX
    BgsqhkiG9w0BDAoBAqCCCXswggl3MCkGCiqGSIb3DQEMAQMwGwQUH/8geDUwOgGFT/GMahOMYgUE
    76wCAwDIAASCCUiNmLT2hXTswIKMeYiIEK7qqjMwYfQ07Fc11b17h6fl0Kl7J9k9kauq74JPmgHs
    UwkmZYe/FPFXMcEULJQT47AOhPkZAnzZx0qsy5ibuXvCezMV7fyri+JTh8MUrgmhv/NVJObHjPUv
    QVmhwPfyHyj1IBqqVa3YnPg7afsLixicSuSODyZn/xnMY5Gt0kDOTsZsPN+7oaJCP0+MCGZKcrr1
    qyESiFaPHktLdMsqfmk8UHfaAAurW/Vpez2ZX1xpaPgdlqr2yxdVl8TwO0li269itoo3ZoNXZ2WN
    5Z13mN4/OeFhMIPCiT37JM7GHdOnLUdeNxmmYLrL4uzDIOSYua/Ah46PfE4X6pqX9yyGtE3OaMaq
    Ryu6Ym7Pj6ejh8h6icog/6mRqDOk4FiB+o2hUzmFj53g5VvoHmKMOpTy/kJv1osKB8BLaAhr6DG0
    UydvbwzAP4ks7ywBx/4mbIgZzirbl2EYOPIig5a3EhqXpr4PMkE6+Dh2Hv5JFNt22Oxnw8Y0wBsV
    GmIxcX1OuDQb90SsF1CSulGTWZFhvpKxGBDmfCe1j+HjSBSd3YyUxjFoAXBZ5C416xJc5TvmLYYk
    0ED1E8n8LBGkUutFugmpwvtWUaOW0ogogWLbkgbl8YTQFIksAJfBr4yR3WIZA25ev1ZMsAbN/8V5
    1xyZ5joj95WDrrFn+h7cgvn0Q02tRb+bG7qZfa1E97qx6xDsDvva+c5iyuHQ7qCJbD2JhfPRLAsY
    CJ7rqzxuorgT7i62PjPHumDY73kyeJqF2XxHypRKZ+0hXMkTVV+OnMyStOolGXNOEf/y0/lLrLt6
    Ym/DpXV9nOahoI4NZ0Qp3nYkP/asJmANWSAVlc2FiTklvlWcOp61Xr3a7c++f3WgHKR+wtOU+ERk
    ImyJSm2X6Txpx1jkZ6ez+5+iH7VolAa318TWVebWf1OL+XCaLZj0oa4Ad1VaVL+8A1wUKDF4kPpN
    4HuYcP0Byub7zaFSdmO7ciliMeN5tdEw8lF5Bv/C9Wg+HyNszJMPMOp4YuWBKu/O5nbrdd4n4ThJ
    w8Srpt4c6Oe7qKYGCSoKeVpcYxcnIWbUdzZpP0pqVmVfZgBNmt/JtM1JsJ13obuaerfCSROPVRSA
    OV+fSz70e4nCslvBPHarCkaYjl5tOrIfZnzir7d4ioAwg5wlOoEJU+u/HEVGdfMoQkviqHLmztWk
    BIID6Kpxe+Wj9rox0ZYrSbX6+0xMKJFOhu0qBIID6MQ2Tr0oCIMBq0wiIo4mGRyrX0+OGDCcHozR
    nTVy+BCGQYjksKN51ZI4+eVQpbMyPN8RVxWkMdXzXJzBMFYrkBDJU9OoJxG2iCRMldjOEwj8ybm7
    aDXqkcHbMLHBHL+4R4D/aTywZOmrK1uVdmBuOMkbke1G/TLrQt0Q1WRiQrutlsYO54mYvnRIIHY9
    SKCSap+4bsK+pDKBLfCXtP4uL2O/wV/hm5o0hfYL7/edwOFyKMJw6dQh2ilLM7IayMZSE5aJSnyo
    wUR8/9i393KGBCDmL6eEbpIFfIzVLsV2FqiuVB5Y0yITh0++SjpkL+trQ5QjmCCUTmMVnBh5oOpR
    KgQlPFT+FkEeWhZeq/CwyWhsE4vts0tbhlaz4QpDobzvqOprmLRgAHw5DhApehW/568bO58VQZCK
    3uqwXRjFpmPoaWP8pibZo0Rule5gpENJQaKT3fUW9PDQazP6fjUYh+PMlPr5PvLs53FNJerkV2OJ
    zPtxYdV+YmU91fGsM2/uDumOUEx/I9Tw4455rn64bDrFN7IZtuPG+hBs0ci4M6s4arzaG3bOJELP
    u6N+ZZipx8rp/Qo+mNO9QtNJcV4dqQ2DfelmDnBtWU1+IR7LBrRa417CqBQjzT0x/8HRd9Ka+KuT
    JekEIDn7tkgurruSrxddiEVnxHvqZ873rpPkS4YAXcoEB+eA5RgaOOktPpjAC9TpX3w9fiDY2oXy
    fP+VUmxLeOHaZKrXrHMlX2SF0olrbQLgIR3WbQpxnS1aAfogQ+h6jTexw0S0hbEv1uMjb7+Ogc/f
    jk3iygjlpjTS3thg8WZXL1XEq+A6TJbHYB+R+fpBl5Xomp6UJExE9BrFl1SdZy+/hgh54jp7xSvl
    KwoZnAp48XHfuXijJGGH+ejgs0R0H/1fAJBnQM64wES5AbM1D97GCBId7ByNcSAY2wsWZGU4+XY9
    2FLCkH8W1S4tzUrFQUu/0FGsJlRKxdopBfOZM7tMtDxMdokG40j436KEn0kMfoa25GPcI3G510D5
    6VfM63R5mYzpR2vQ3VVUs07XtfpYVmz4LxFpAI/N8dTX/67r/9nEpBcRuz2Z0+OTPjqeNh4APZxv
    6qh1F5aRTt6hkOSl6cEzezpZzvC/HboQulABRpmViohsdthUUJ5djSVnKeCxajzsmuVEaHtYB+l/
    hHxtdvgCtqeubA/Jwzeh4GtnmpaNqhxP9S6q4Bzd/HMXVK4z9khWd9BWzIr8kzR+AzsRTIDpmKl/
    mCO/i7mmM7F1grzl/XMhkfDCueNHa/Q4RGj2VM7YHF+Qh/UEggPoAZdN42pcEDuSzfwKR9/ONbuV
    nlKYO6QQ8Dc5BIICT3Qe37WB5t4OAJzywiNxR8Mlk2qexSv6zoKavGdArDanRn32fDvgN/ZAVuSt
    PmNIVe6jNyjVJhRCbyIf0KA4fFsgjpwkd5GBynOnbcAVSdcwsCkmbusTcy0GnEcjiIFrF7VWEebG
    /0A9Qxzlg3xsfRNudDD4GM2kJ8mD3Kdk6v+YdefKb+SSJ9Zj/7PneMqz8OlB33Gntj2XzDERyQUx
    3TEytrexvVJUfxGEyLAy79Tp0wGHEWMdkKD6WZjffgr+wohlAVMa7wkjB1Dvn/qPFG+y+PEnnktS
    cKZSiQX/A1VNH2YQKlUMy2ma0QX7mbqOMIiNrp9t5yISEpkzYJHTIuF1NF8QKBFo7WBOPzstiJB/
    DRuLRgNCIbOT5fT/DmotwPfSVNBFFoTfFdCMUGAScMrIZSpsehPkLHAwOGm5aL45V2OBFRzQxcwY
    OGJiMCgOEQ/rgQvd/tSswLhQyrqT1pV8z7dCmZKCRgVsmcUN3VMwTKVawiWbkY9RLr0suEO6nQ+s
    uj7cWQ+QNMaOiD4Cmd5Peao2L2Yq1/zvs/ZotPoxXU05wY2UqJFCJZuzz8jqGlbOlaUkAkg3wYWz
    oufQ8keTRDHVMYGIMCMGCSqGSIb3DQEJFTEWBBRXVQGtF62kFmg7jfD4O7GtAVb0gDBhBgkqhkiG
    9w0BCRQxVB5SAGIAYQBzAGsAZQB0AC0AYQBwAGkALgBhAGsAcwAuAGMAYQByAGIAbwBuAC0AYQB3
    AGEAcgBlAC0AYwBvAG0AcAB1AHQAaQBuAGcALgBjAG8AbQAAAAAAADCABgkqhkiG9w0BBwaggDCA
    AgEAMIAGCSqGSIb3DQEHATApBgoqhkiG9w0BDAEDMBsEFHQysYk7WlyQRfABi9ibmmZnzlDUAgMA
    yACggASCA+hi6d3xUj/xRTRWns3Kf3y7OJEyW+JMOLcQ9diH85Y/qhgW7sYGYrgIJrQ97WmPSIie
    ydg58I8qzwJH5O+kwfZnngLrlqfWoZX6smpXHQnZTHHhpN6ZltJzu9sEXYSDgfVQruai3wOigUWC
    X8D+Hpb6WK4r6fUzHMTDK2BpKMoDqwLN2Djz2rl05O6Zreog2QmeHKYITjyw5peSIdn8Qxta1qQt
    Wn4PFY/kQtdroPFpKVSswWFBp7Pi/XC+TzI0cO5U597BzQ+QouE1VmzxdwqT/oiGquGNrjJKkjmK
    yr3Pvtzt6RiBuE6PX6jD7smSmtuFd3pISd3EP7kYmcxIA2VqAN2sAnZKmxwRqFamWmng3vIAdWBT
    1dZXGvtVJhacccjd7QSCA+h+dbCMCePo8yFVblMTvSMX2HVV6bBKg45GeKlli4jglfSQNVSIQM4b
    sjSMwuh7fSeVlOfeU52iWYWyr1q/W9zWHg7chDczyqSY64bcEiQkI3BlPfy9V8/wTybTBCiRoh86
    /zMaQkM+EfpSQhYGf2NkgT1X94/WMhlGfGG+glpB3oAsVioHUxxAJJRrW/zkijVDwvf8Epr8kpsj
    goguq/CgfecaB0vzuBLwOanEaAAywUiV/QMXWf5omxA2G3tg8C4qBBlTA8O9k8cDz31yhEJeQVIl
    L7xRWqASeXSX9/zm7jKl7anOj1yIPRoC4RKr8L2/VgWzVbZCB6oMzdoRa55UoOJjEwqgHsF2HDcY
    DuM2KJd5Wa172138MHsRglG5bvHil9CzRcSy/z4zX3kxCj0RGsC1nX3wzANgHgsPiqAj9iues3tg
    cLN+wUYgwyLfF7tfgXWZon2WOySsPJoXtQ/GyA4St8X4qp66DkwRuMtaqG6ydOkfmHa51iaF42gY
    mPobS9H736TRY6HfvyI/CrEHqM16g0BFZUEL2j2MhXoaE51inYTXYX6axfTsrUKXvNFWIiebJb2+
    nZW6k8XVlgV4OUeW22IXwDVmyumN1cbR4E1sl40C2aq9Th8Fb84kUxc4Q/Gnsh6P3+hy88IjkPYc
    lkkOJXBraE+sMzs1RBnPmMr5uu7rGqY6Jl7fG/ed2ISTQmxJl5lbDeDu6V26quyy9KhKSUqprWqP
    atwOxRlCgoC95FWz9i0iFLGJYs/sD6wt/BkY5IBLICmA1L0iMxozMt5CveXwE2x/Umg7RLvm0uUL
    qVicT0oEXKNB4ZXg+br0WZ77yuc9FMqlyMuiXYTnb/0nzdViRgWioyzbEGQBOFXvOR9xI/L7qlEf
    aWvMboGqKBiwYVwlqABphgUY3yBjBXVqxhrnJtHvjwDOV0rZiwXLzQZwOASCA+iMxsq5vryqScm7
    VAxbBP03B8aarUeuFjj3Lq4oXCJXeXvnn66CVCrJf41Lj9XoxNQFhD5f4Wv40m2v6S6dffHrMftj
    QYHFuXRScCvYFvulN+joJ4zvv6e3eNHLEP+qjwx64K77SJJfAg7pIwFDuXQrxq+vkdDgk4gr0WwN
    M+YBDGSD6zv2ek/SAFSRHQXs1wxbDnYd5DCyR0VLFthUgwfFXhUNRf8ZEUbNhYOHVry0TFFC1J9C
    hqum/cd+5tIgp742xbkl8QtWjkEKMRIvHMxqjZkN7iFhcZsaPyT2OriQwHeZW+QF6YhEIkkuNmw1
    QGp4H4H5aMqxerYVt5MIa1lenmDL30jpWxrZ7/LZMjXBxLNPkK4dnI0Y2N925EtvBIID6HO6+XCA
    UTHrNvvi64RmN/SZZ9oqX6H4K/uSpq4VYqrlKVIEyZVhA2L8X8Q4RZIkSN6/HPSR1Z/CMR8xqaap
    2uqPppifuqpqNGBLYcvFxaonpeyPoe7qkbS0+cSolLriGjNgLCDDzHUR+AiJdOR62XIJYKt110Rm
    yC3cAIHMazcf21YhL+6PJIIHWAi0ff5Hpab0zfEvlmRhZ8vErVSQs2Xw74bJsRmYKmE2UQMBMhuY
    IslSHw1KxN0HBecxRuKoW9SMpwg6n62TIMIuNvp48qcWWUQNQ3unY+Io9+EY4aCOlWvUkMYJxyFQ
    Zg1XTwlZ4+MPjU6IH/n1GWsmLz/OuSqeAH/VQ77SSP9XGb11TcVQF0A13PdJAE2tkeWzCEYLCKDh
    NlOfYZvyIb+kP3aW2Jes0e8qXAGsAqjr5DMF7rHJKxbhKalno8auN04yGF00z8VwXpMgR413l/31
    pSAmo3qaPtETXoMsQTxqElIah6R57Q9d2C//hgO5e3d8xb2+Vf2qmXlVGz3ar0yJ/iCGO4eC+v4i
    P7WNhHq2NquYn8rI+X9YnZnJkkzp0QRT8RY2y+IF49rCKym8hRT3xdm7YkiFX3Jyq/siu09r1da0
    ESMVciVHME4OSDoCC3tbhqJsT7dvj/Y1BHa95OkFHyUrgSl+jOacBOBh12jm+whAQHAkDaljAGSP
    YwpXU5irN63RNdgx7Gj3arFzXSuK+8n/oaouypbYsYGiFhjfpiHDQlnpjyVmHoKEOlHJTWuOhxjC
    3Bz0V7Qh71EimwMie2HVkjSutze5FLU9qgRKwg3juqqRZ3d9ePms4ORtAPZFMhooHXcnpIAVXxKV
    qXo6B/p09YPe4ZF6GufRbVlzbhB4Xj9WKpfoh9j6q1AXZjMeqsKCXJlwQf/p5KKTV7gIByM/ad0e
    08/ffQP7gpeeqhnmXBckoDqTMNdHKpdUwwSCA+gTJujhZR7PipfwPU1GHoEo4SLVBH6UEEHct4Zx
    XGdx11v2X9ZJht0LJWhXF6X4Eo7wE9tJMhWIU4mwDnzhxsVIMYEKtSEeTz0tR6kbehT6/2dDpnGU
    Cg3B8GUaIYX4BPq1R5RV8tIg6iconAUgWSvhzb3KXY9Rl6cArVid7qVn7gHx578yP6JAcLN5TMVh
    Y5vXvUnByLOHoYSzECYxuhrn9PQO3096bxwi6dkegHRVWnLJJ39H7WSz1eEJpRH/hos+dBy78Sxk
    YipfVONcl5Xn0k0U66e96kgHVs2HfLDBmv51na+W0lAiFd5YVPUERcA3wRNYjVOtO2YvJpANtxyH
    TaWTE7l3J7ijeLu34P5O/07Lg+/IyrddoV0EggPoHbEHnML4txmfJN3qbMKYLqyH4XvX1mFmAzES
    ef+2ifOUVvhHKX5gtrDQq76cPUH7c+SEO01Pn0Jj/wZR6p5CJLJRaEEJ3lwgNUoRAGtPdSf6vQs8
    9M7EvsJpdvGY6ZTmmPgkhM1Ajt+jUvbgbFygkTuNdoKqIPfEYfvkefokMQtIUbAYS5NsKyBBgPE8
    tJ8j3PIGBH++VLzPNZ2e2kPMiyAvfCQ7f3js3V99Ji3trU8UeIosH7DFWakGsQKbcbaQPLAFLYJs
    vj1tXwCdij+leVjgJN2rfRWAtRR1OR4CCtBkmsc1T6l0nFzL5/uJ1YvSgZ4hzmEbJFKcrrnmyuMN
    Jijo3k0vj1gjlR7hjaATB2+eXH8ZjyOq6wzyZ9+ukTLLeuyM76Os6eyStbuD7fY2rTk8H5m+cOwn
    ZL2SVKYr0ZXFjioixLRybVa3nzluFckJlsVKoJBHNqWt0Isj1YaSxrCAnYA8AKsv2VoJwao0tPKB
    y6J1sTT/7L0cIA+l0D/yCUgnUELFRerqZ3+p1rMRSzZ4BdAFwVH5fBOKvTqv6LcnR/J3HgqTeDOB
    DaaU88h/KgS4ajL1A4FgcbKML3DaxZ+ZNAXdECkltPSwXNkBUE0frYG+6yaaY5/tbS7lpI0APM+4
    rPc+xKFEb5wAAGhuAj2ehxD8Yb+X0RM8N8QtuYlkGT8+AoxbEd+Lx8LvLeZrl/THiMl+yI+Fy64/
    JSFXPdt7oaZSsiczX8nUfcoR7LywxGkrmk1OTi0obU/1HVtn3dHG8ECBV+3y0B3DLuuiwv1uikS6
    pAyWRtYi0umLumbU7C+Lpc6EiCbnnUR5PwfrKK7BcPB+oZiNyVZauBrgY4OcGxEyjVGT8jrnmz1k
    rZutSigH0btik7mE73y3hXPVdpH+p8uIjzdVsPht7AlnMiWVdpqqw/A3esI30HQPj9hHQKEsuhMB
    VpyKY7T14wSCA+hFJRoQfwAr4MoKtIkHgaI8RPJ57r3Mgfj9IrF8udVDvSulle6U04uvCM6zq660
    iPC1+VemtYgNJM8atxtbZkkMPw/CUUIW4y7LXkd2P/0iqhs+Hf3D3Xqo1FG+vpm063TJqQwfIgIO
    sKAr+SWt+EtOgdtM9+P5yIX0gZk/4Qj+Oc1eRoN/oMg+1k90XYCVGoqMF0zIs1Q8I7CYYcejkKV/
    nnFufIWQZtPGCFKZ1mho50hXm1d97gcdTaNTCRkNaT61ABGzI3PrCtIJTCKuSGTUFtND8UB6TJYp
    1labTZLHZzSKBOZeCXe1pMZlr6dKreD0bWQrZRey6tKliCtkGY0dzXp8MBIzbm/UX6LkVFXBSuOt
    wf6jnQSCA+i1ewwzZacKAmi8a3I4ViQaCdWu3k/giwg60vn4CkSQpPToocyt3iORr+8MdB0uA8+F
    EGnI7huzU8ZNB3iln3c/p4J8TWnuiSY53PcYYrG/phiZcnX9+62Vz2lTvbWlduzXSJFIXfjGKmlR
    idkbeuxxptgFVYi92yXFWY+BOx7EbmF+uBej5aogimq7VLceI8LarnM/8yt1A20JYqxYsYMBnehP
    9IoG/izScenEnEbTEGwRHR0vmkG0jMIQDfxyYsFiB0g2C+oMG05pOp5lEBEGNzhnBPP8WuvrhfNp
    jFsrvcuyF6xK8QDu1lEHX/aRX5wldHmks3DSTpxCdZxFmSFYNPkZoykmTggYfZvjMv39KuvsbCcc
    F+tBAhueRDupAjNcDV8SQwIaF6Sd62RRq7LZUaB0/kWAvUbD8qaNq1OdiIc5FJkJWYEn+G3sasW9
    fpda7u9iEqaXY4CEqxzj510nM/aC5nvqAsczMKXqWQGCUl8crfefxWsvZ7kDAx1Is6AYYzeIFRKj
    NdnXOInnn6ibuQt2vI6xVzK2X+E2yEYTnIaAZxm1cpWskzF2/JCF2q/vECKvg0ANuqJqBXRY1GuN
    bDS1Tr428X0AFDX3uU+hKNP3edxbY2jvlG22rWTmDdbbYReZk9zP1orIlKk/TWwpJdQNAHVVx+tv
    L1OlT0piGBERk2PGWpmSjD07pkz+YJC1JZcCHWeum2pGqTL8wPV+jOZ2m/nJvQw4kJukQEQQ4RYt
    KWahgnWJy1Lp1M1igpzemSmd8MzPu8MNEn2eFnLmGZBJJjP68kQ/BOgQxIxyfGeoSE6wwTE+Qoqi
    o5Ba6GlWunIXai+SJhxqwgKrVkuOwWhuquclXQzMtjwtmgfuyfUorHvxC7vJAJh0ixTk8deToDT1
    ch0eBx2nIKVI8pCz2gwX32mwbrYSslJi+l9EmJWAHTjb+aAvn1gEhW53P8BJGQSCAlgDiS1sjkN1
    ZOoeKhNGeaIsm209QKPyizGSwqJpB82PnK1SFxVAPatpi6kytHVDnp+BeO+xxX8XCpXhvUOIsw7L
    EbHHcKQarQviYM6byh5qsJeY+Nh6CqomhDNbxRsLnvHivawoZq0NZALJRFXujpCIUv+QH9x6dsGV
    HpurojBFxsg3YvYxkYaX1NFKH4prsa4MzBSaQDYr7Agj02cehYX6uakN85/asWssq9qCqysQgGoQ
    dcEGf+HBL2je9ttTobdC3j1OiFYa1jPTBVdR1jT8q97JIBfR4GRgwRO5sbjs5QJjAxiBenzUgDuV
    C7DS39jTrWvps8hO+diVXNPyGtCr/apdBKuxszjHzB6fV2/GeyEWBIIBUgf5YUpKgTfSf5kgyrAV
    DGYoqN0p5xm0eYAd7vunNzFDrMg3lOwkXltnbK3VaegH+5IG6STyxhYu5aJiclfgrXriHIEy7Vyx
    TqacgnHbvfOZ3C7DTsrxgPJ7h0EBqY6u/hfzFFpe4sMqQC6NJgIe/Z+UBCoev/eQJb5q/oEoyqFe
    4OWM2dNwH7saPSfvMC6B/F/STglDXWzX3ykmsl9eE8stSti/i/lL4idbAR5XxxxP75bfFP/b9bia
    kM3X/x8r+P3h5SVT5fvmkOQfDAocXonUb765yejl6zuo6xJ/5lKpBPqyAKfL1gLcUdOCr41dJPZI
    JL6qhkruTP1Qshg8ireHlfOdCCyPQ8ToFjJ3uvKwcDBDGnSNm3lclSecWxWRBX4aQz/nMPkO8qTs
    PJwFO1HBTO8w7CwJHzD7YFxou0p2b9EIyuZRAAAAAAAAAAAAAAAAAAAAAAAAMD4wITAJBgUrDgMC
    GgUABBTIM81PqGfq9OuJKVgvmqYWzp/VeAQUiWCXqj0Jzrz75lO6r2KPTGlyhXACAwGQAAAA