---
apiVersion: v1
kind: Service
metadata:
  name: payment-processor
spec:
  type: ClusterIP
  selector:
    app: payment-processor
  ports:
  - name: http
    port: 8080
  - name: https
    port: 8443
