apiVersion: v1
kind: ConfigMap
metadata:
  name: ca-pemstore
  namespace: app-eshop
data:
  MetacortexPharmaceuticalIssuingCA-chain.pem: |
    Subject: description=TEST ONLY - NOT FOR PRODUCTION - Issuing CA for industrial plant,CN=Metacortex Pharmaceutical Issuing CA,OU=Pharmaceutical Production,O=Metacortex Cooperation
    Issuer: description=TEST ONLY - NOT FOR PRODUCTION - Root CA for industrial plant,CN=Metacortex Pharmaceutical Root CA,OU=Pharmaceutical Production,O=Metacortex Cooperation
    -----BEGIN CERTIFICATE-----
    MIIFmTCCBIGgAwIBAgIUNtHWOn2/8lCDltfQJVh+JHF9Lp8wDQYJKoZIhvcNAQEL
    BQAwgbkxRjBEBgNVBA0MPVRFU1QgT05MWSAtIE5PVCBGT1IgUFJPRFVDVElPTiAt
    IFJvb3QgQ0EgZm9yIGluZHVzdHJpYWwgcGxhbnQxKjAoBgNVBAMMIU1ldGFjb3J0
    ZXggUGhhcm1hY2V1dGljYWwgUm9vdCBDQTEiMCAGA1UECwwZUGhhcm1hY2V1dGlj
    YWwgUHJvZHVjdGlvbjEfMB0GA1UECgwWTWV0YWNvcnRleCBDb29wZXJhdGlvbjAe
    Fw0yMzA3MTEwOTM4MjZaFw0yODA3MTAwOTM4MjVaMIG/MUkwRwYDVQQNDEBURVNU
    IE9OTFkgLSBOT1QgRk9SIFBST0RVQ1RJT04gLSBJc3N1aW5nIENBIGZvciBpbmR1
    c3RyaWFsIHBsYW50MS0wKwYDVQQDDCRNZXRhY29ydGV4IFBoYXJtYWNldXRpY2Fs
    IElzc3VpbmcgQ0ExIjAgBgNVBAsMGVBoYXJtYWNldXRpY2FsIFByb2R1Y3Rpb24x
    HzAdBgNVBAoMFk1ldGFjb3J0ZXggQ29vcGVyYXRpb24wggEiMA0GCSqGSIb3DQEB
    AQUAA4IBDwAwggEKAoIBAQDdlBj/rDiHVtA8VED1HNmEzwUHfVNQEoTbUO5obLcg
    CdxZkwzHM2UMIsqixoI1b6j88vKsh1GnvvchgtqZqt6IUx05MP3b6X1mg4tR9GvK
    eCiF0JsxJ+jr4Ku2u3zE/plpEHoyt9bBlyCWmNTMrmoNeRPtFhPsgHcJag3T2Ry3
    lSShVFUNIODWYDl7IqmPP/I8tt9G2dhlZhXpXQi7f8qC3rOhfmiv7GaI4TEe2o8G
    yd5XYdunxNg4qrWP8FuUswxgSaiZyhjmjlRRrNumrMkELGU5PKp48uGIQ42e/1vw
    OSUt1HCRFqVbtxbIFEJLjoUfXuLSDUFjdHOcVRqVACYxAgMBAAGjggGPMIIBizAP
    BgNVHRMBAf8EBTADAQH/MB8GA1UdIwQYMBaAFIsRfAHNgXzKm7EoH25DahAeHT+h
    MIIBJgYDVR0fBIIBHTCCARkwggEVoIIBEaCCAQ2GggEJaHR0cDovL2VqYmNhLm1l
    dGFjb3J0ZXgubG9jYWwvZWpiY2EvcHVibGljd2ViL3dlYmRpc3QvY2VydGRpc3Q/
    Y21kPWNybCZpc3N1ZXI9Q04lM0RNZXRhY29ydGV4K1BoYXJtYWNldXRpY2FsK1Jv
    b3QrQ0ElMkMrTyslM0QrTWV0YWNvcnRleCtDb29wZXJhdGlvbiUyQytPVSslM0Qr
    UGhhcm1hY2V1dGljYWwrUHJvZHVjdGlvbiUyQytEZXNjcmlwdGlvbislM0QrVEVT
    VCtPTkxZKy0rTk9UK0ZPUitQUk9EVUNUSU9OKy0rUm9vdCtDQStmb3IraW5kdXN0
    cmlhbCtwbGFudDAdBgNVHQ4EFgQUGv3Mff3LwJ3v8U+qwe7FWhMs6bwwDgYDVR0P
    AQH/BAQDAgGGMA0GCSqGSIb3DQEBCwUAA4IBAQCOhfNvozj6gzBjSO/U0Agsesqj
    OhobtU89hTjZseLXr0Mmw8bmV+Zp4o0TTY3uBYqlGvc67wrwK94FGS1UwMBF+7rb
    o26LsPIx6Z3zGcZePIAw3B2wtn2Z/9cFQ96oRtAoW/+IPg+iv2T9ERYVgRXylFPp
    Mpqn84fi5cBhtYKXlLzHLtOsSqEQQ3a96/f0KKH3D/CHcnJUy5i0o21Usrlm4j0Y
    U9QAM7xx1XOQ/NFsdx3qvfDGXt/NgA/+6AyzGMTsPWcgYuLtRs51qU2TET9GO7IL
    xdrTgvTlK9s3grGRpGK/oJ8VKft9+dUX2/nyjeUXqHvt4li1nlQZoi64a6I3
    -----END CERTIFICATE-----
    Subject: description=TEST ONLY - NOT FOR PRODUCTION - Root CA for industrial plant,CN=Metacortex Pharmaceutical Root CA,OU=Pharmaceutical Production,O=Metacortex Cooperation
    Issuer: description=TEST ONLY - NOT FOR PRODUCTION - Root CA for industrial plant,CN=Metacortex Pharmaceutical Root CA,OU=Pharmaceutical Production,O=Metacortex Cooperation
    -----BEGIN CERTIFICATE-----
    MIIEZTCCA02gAwIBAgIULyB4mMGZqDeh1M5TriSOipTF4OUwDQYJKoZIhvcNAQEL
    BQAwgbkxRjBEBgNVBA0MPVRFU1QgT05MWSAtIE5PVCBGT1IgUFJPRFVDVElPTiAt
    IFJvb3QgQ0EgZm9yIGluZHVzdHJpYWwgcGxhbnQxKjAoBgNVBAMMIU1ldGFjb3J0
    ZXggUGhhcm1hY2V1dGljYWwgUm9vdCBDQTEiMCAGA1UECwwZUGhhcm1hY2V1dGlj
    YWwgUHJvZHVjdGlvbjEfMB0GA1UECgwWTWV0YWNvcnRleCBDb29wZXJhdGlvbjAe
    Fw0yMzA3MDQxNjAzMzNaFw0zMzA3MDExNjAzMzJaMIG5MUYwRAYDVQQNDD1URVNU
    IE9OTFkgLSBOT1QgRk9SIFBST0RVQ1RJT04gLSBSb290IENBIGZvciBpbmR1c3Ry
    aWFsIHBsYW50MSowKAYDVQQDDCFNZXRhY29ydGV4IFBoYXJtYWNldXRpY2FsIFJv
    b3QgQ0ExIjAgBgNVBAsMGVBoYXJtYWNldXRpY2FsIFByb2R1Y3Rpb24xHzAdBgNV
    BAoMFk1ldGFjb3J0ZXggQ29vcGVyYXRpb24wggEiMA0GCSqGSIb3DQEBAQUAA4IB
    DwAwggEKAoIBAQD0qKN4F6elar0wUEXRvQYA4+oPT5MQ5BUYSUi1TQFPI5AMXoEN
    4H2RxNpLBR08k8Kq7GDRMLl2dl+lLTlejEP8Tn7ixZJd5FFlnZuZiIscx5l6zj5u
    NWTsx0GuWWSRNb9qzMdDSt8EGkeRQsFEiqTesQ6/IQlOSmdppHq6JqdNxRFXqilM
    FVBBDPEzN8BiWx/MGpB7CMdwhe7OZLszus0yw4ZuUasy+DT4zJPauhHdWRFCK3oA
    X2tRG4LVJEgOvjuL8S0MgvdnpM9bEXW0shboLEqynYsHiR3MkAKRaK56XgRBmX1O
    7ekoBOD6dmytT/zekb0pOKFyxSEuSSC27Th3AgMBAAGjYzBhMA8GA1UdEwEB/wQF
    MAMBAf8wHwYDVR0jBBgwFoAUixF8Ac2BfMqbsSgfbkNqEB4dP6EwHQYDVR0OBBYE
    FIsRfAHNgXzKm7EoH25DahAeHT+hMA4GA1UdDwEB/wQEAwIBhjANBgkqhkiG9w0B
    AQsFAAOCAQEAjGyICMzJZqyA+jiJq0tLZ5FQxRrD+c6uqYYpl8sfAAlNwNNqejWs
    gz89nlBanWMBjRxHoyj+gMn6KCN8ZilJKLTQ7jbPc6XGuhGpPdnCs6A1a4VVd8sK
    vkShy72GUoaXyqZGPE8YUIEgLG8wmOMlcWvKt18+petNmVtTBTCKWLYh86AVa+kU
    XlI31iD6Vd35C5UuPVbaf8RXFxpllc2Y2TyCVHAa9+bcrF2rXOC0Dnqcdgo/sl58
    gjC4GG1c8SLktKz6nnhZdQB39Tar7ndriOVqGab+C2pgeLXtcHIta8x//X6C06Lf
    Uev3H8zqvGWre8c2D2iBjj9exIGXu4/dSQ==
    -----END CERTIFICATE-----
