resources:
- deployment.yml
- service.yml
- cert-secret.yml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- name: basket-api-env
  literals:
    - OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES=true
    - OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES=true
    - ConnectionStrings__redis=redis:6379
    - ConnectionStrings__eventbus=amqp://guest:PFV8aZQjil@eventbus:5672
    - Identity__Url=https://identity-api:8443
    - ASPNETCORE_FORWARDEDHEADERS_ENABLED=true
    - ASPNETCORE_HTTP_PORTS=8080

