apiVersion: keda.sh/v1alpha1
kind: ScaledObject
resource:
  spec:
    scaleTargetRef:
      name: whoami
    minReplicaCount: 1
    maxReplicaCount: 20
    triggers:
    - type: prometheus
      metadata:
        serverAddress: http://prometheus.aks.carbon-aware-computing.com
        query: sum(irate(traefik_service_requests_total{exported_service="app-testing-whoami-80@kubernetes"}[1m])) / on() kube_deployment_spec_replicas{deployment="whoami"}
        threshold: '0.1'
