apiVersion: v1
kind: Secret
metadata:
  name: webapp-cert
type: Opaque
data:
  tls.pfx: |
    MIACAQMwgAYJKoZIhvcNAQcBoIAkgASCA+gwgDCABgkqhkiG9w0BBwGggCSABIID
    6DCCChMwggoPBgsqhkiG9w0BDAoBAqCCCXswggl3MCkGCiqGSIb3DQEMAQMwGwQU
    6bBs602cRoUVubXRZRj6lldFtTgCAwDIAASCCUhHq8LtG1HVUppg/j2h55YFtFhF
    zGSoscb0SajiFuP3pyHyh55PjFcJBqAOEnlvalIvklqr8v+jUUwxXnoGGPhzXbNJ
    7aCbcJMTdZD5yfD+2CE8o7/RR58hjIOaFOEdyTWx3WxxvxmmCsTUKqtLJdpqQTxe
    H9rep+t8lerKMX1lP+AgF/gN2woc3mLGPN9sVYSTXrM1I09G770ci9s7puu3/p3u
    22R6lT4v5s4+SaVlXM1vSMx/P3vsrN8e24y2eCS8Gpq65qheo7Q25Kp473jDG5GB
    T/ak9GHPQEDA+T4sh1Ri36/buD29cL0arYIvGBGcshwqsuoknk9nzI6ovBC9G6VT
    PLfYJagewYVFJ4d7jbW5ww9p6Mni/ioQKHtx71ZwdrsHILYO1Wby2VQdOIXW+Tt8
    cWR45csebRys0t3YdhomOn3ro1cFCXAWj7AXTWejylGk3Um/nXSdotJte9ZTmFpl
    nHy5d62FJAQ4Eke6sNFYAblKLhSAJbz3JGKnzRJ2DxeGfnMoODKfJPNhX76kV/sO
    z3R4qz5fxkzGB8u4H/SPkKb5C31mgvsdgcrXzJKUq2kfFeTC93XcxiCrZEA1hr/d
    sSFqsXj8noXHBDM6zCNVq5ZkzT7azElsW/6WzzIdVqGCuX0SW5Ul1krcpbCSfQAR
    jylKH8vAuRP5KsczHRzX/WLoUZbaWyhSQbF8wZ8n9G4VYSWAcOCyDFc7Hf/s3AEK
    PLXz+87RmwtQoeQCxpa3uQX6S03l9XZDHy6VsoVEDvMg9EPzMcftnGhzRRegtpl3
    AflQthXvQlSvqecJfuPnkopaaQGjMXzwZp5lEVSwEmiG5ayzb5Bt31L/2Yc2s4Gn
    iust2TSYJ2OWLxAKclBuCiq0kcvwzLXBHmn8/BdLPNV7LCsDXdcuxeNP9UjMcahy
    sj9w1XnWpAkLGxiApGXJ7Sf5CeWRpbzBiY+ryNLqVi2k6pDTucJxNoU3CR+iqV5r
    vcf6SLR9W6pXOaaIRRk2C5JT3D8VcIyuGtsb5vhtcDbPzbsgArM5/otR37jJzCLs
    5HIeHNK0QxXYZ/HU8Wo5x13LwudklcU36YRLWC0x+V/4eS7tjE4YYq+s2w6DptZH
    sMLguQDsI4VlFQvCdjBsCqDUPfdPHjTmkba4rszxgaUH5OfQ8wO4MM1wfprBLV/y
    JEy1RIwQWb8czrfXWdlGahYqBIID6DHfcclGb2W4wu6t75FlYS+GXwvpzXv3BIID
    6GUGhoTi/HlyGRCzxk8Xt8mcy3W32DVhLgyGlSRiUnIFAjE6kh2wpveOg8ctzDCw
    W8GOsP4ACQonFM+JPUluRhJPEYIKABsuBDsndEzHPAcDHokPeNn9a7VXmeUA1Uzp
    aAKXIzZs8QKNdvC/a6KQ7/jCAkSiTQILrdGeopU40tRYZMrIp2Q+XVx4MnCc9mNa
    kGMG+kf3n6hvGJOHb6Lg1N4o51f++bhXcgH4II4VYaSpwULpJfSkYBKLInQ8nubf
    qBbzX+PiGvS2FMtrPb4Zd1w1Rreh3z7uys/vLHDeWF0g3YEXg9HgfWnqeL4enWfY
    MYd8pjjO23oyPEma/871NNG1VYPHOUbERnlFmOOI/fiHWywuPnQEUo7WtvtXyLCj
    7YFhqAVml/lWCtQMI5Z37+sxLL6tdj8MgKnJkLI01PkB673By3jQU85uPSRp0ykl
    uDSWcMiyp4zizfFhrLQeEwH/Ks3/3q65dqK6thx/+/b9M2dMtEbD/02nMtl5vhVj
    khyBAaq2TnRZk2BerCRPPYlPHv+m+tZli2vVgsIxRbxWRwNKzbA2oqmfBPmhV8WP
    oiUtZA22rrVdh0jbxJU/6swBtgYSomhZiS7gLBXT4rN8Wmh54E6LkjynzcESoB1w
    3uSoaVVoXJ/9KRbkvlUaPjSCuGzQ/q90Nkijm9tIqm4S+aauEgTo7tnZbuuHwoOl
    rOuEXABDUG9R53UGjsFMu5+6Px/sOszgQh7Ez8ib15cTsERC7x07v6kr7rlDzb8j
    6J42MmpjZp1jyiPAT+2vkMliPY/YayQxi0AmTNugpLL17kmFd8JzxR24aQPWF5/3
    JYeGzAFtnDtc6ki35YUYkZAcvV76ayaJl2haHV5u0pl6RQEMBOIHSzu+idCqYFR/
    YfPnnTbvprQTPvBnqIjfoEfcaDS1sXkv/nmT8OXUNmfTlwNUexqbZDSjGNIkP1yO
    zgAyi4srzgSb4m5m+DMGxbblBJau8ZVMdIeje+bmKNcCiH6TFIE+psisQC+ptqGB
    8T/sDdB09sPwBoUY3nT2kuDRTcZEv7ET0tmGWxKHosm7JN/6c37Q1fyJ/b+cAzpu
    ydrQ/SXYAqAAyBLAEG8ISQ1khufzhdkuDspCAh1CUUenCkMEo1KETu15Ksn8bkxW
    OxbnI57amNdUkeJvFNw8wkTP7ZAsEiTpM5ZyadQTd1UU/1LlDtvKfg//eVr8oYH7
    4n2KaohitFLrrvWiK4Tb9DVf1c2RL2rEohFUwf1r0UvvB+bN6pUD/TKjWoymKben
    2GpPeF5mlkMwbI7r4rcEggPoFlBFNrGIT+Alkdq9anowejzV1wWAHyuS+6zDBIIC
    R5/oyivrLC+LOEvQMVSUnIW99c6L3Te1EmLHZ68L56eQARTJIkkoXhHbQtW2iPQi
    N+QGr1FWuw470H4BnH2SFrYCl4gmRDMTHNTOyEThdtJAIRE7MLcriXFDqhjNL+XJ
    lshG8pIAVQFJoPAtTTi/BY3NWH22yGjrPAfcpoQoQsS4hMRLnu32okN6Nzx4QyEz
    RF77qGrv6+1fnoWJj+xO2y5BQnS+ue6v7DXzc8QeyASQFPguiO0DaVo+dZu2mI/K
    v5bHJ916iZcwukRQyfqHOuXWUtltU7SRXcLKlxUuJgXDBKJKD9jdlAZPRX+0myVD
    3BL7nST2DVP/y/ws1HH1VLUWnVlaZZbcC/+c58B9pxYAiHYjPgKYEItjXPzMjXA9
    N0q3LMV/N7Fi8tRicLaqgjif2YSSxiBvEJY4PYYGi/TofkDPb0sohBxo++fqudTJ
    Hgd6Wv8pdhD083p3YXrzWFn9ZVoX0Y6DR92IMRPsnn6//aYmCd8mDnoF+tOQB1Ml
    mg/SmfERwSSfQ62AF6KNz1TH1HCMXEXI+Z9LIrB2GHLi4o/P4AQdDC4YbXpqwdBc
    KqAIh/OIsiSN2PtVtOQfvrmljafVMYGAMCMGCSqGSIb3DQEJFTEWBBS5599g6XP2
    EkvJDIaGWZyApT/Q0TBZBgkqhkiG9w0BCRQxTB5KAGUALQBzAGgAbwBwAC4AYQBr
    AHMALgBjAGEAcgBiAG8AbgAtAGEAdwBhAHIAZQAtAGMAbwBtAHAAdQB0AGkAbgBn
    AC4AYwBvAG0AAAAAAAAwgAYJKoZIhvcNAQcGoIAwgAIBADCABgkqhkiG9w0BBwEw
    KQYKKoZIhvcNAQwBAzAbBBRjC540cfvjM8O4FUiXslmn0cKUGAIDAMgAoIAEggPo
    CRmwNGBkkjJW4/faWOKW8+fjWPN2U3mWxoTIASppwpQ2y0+vP0GJf9Z41bw+Th1X
    90NLpjp6EvKSEFJ5M0NMFnR8LN65nY/ggvABYP19VICWVsrxlLkb0zUSbfhMYtLu
    VH7sLtFxfM9S0OY955/CHCgX7VX+JH7ZsPsFfKs1Q0Wy0gGk522CPPxsSKfmjJai
    l4CGpkyuE8oHF8HAlzngNvzhN3r7L8nTPH59yk7ZhAN06Sp1JUDreLQmMl0I5nO5
    LxhR5ahtF5/KRqrjLA8XYOrkbScDH0FyjXks2cO7bOQXPaLLmcfuLJHI7fR6ydmj
    qpmPcrNkriu514UJiBJ1rHz+JJj1IdZK/vOo7ej3oF0eVXR5taybX6zCaxmGoURA
    oew+NOyhLoQmFgSCA+goMmA83hb/RBuCYKgGSJJpgI5YIcRG78MRamEr4UgLM4+O
    9Te/EwCeTscEruUYcRvhyx7KJV/HbUEOSMkmRR3b5p2CjQLn8FmlrbVNZ85vgohp
    5yVipZwbJjvA2Mzp6aLdtRs9p6h/DoYVADRFyiG1X84+11wQKdts2sczW9YuIYH3
    FmBFA+vdGcsx4l8XExb3s6TBfYe9eI489HL3XMNkbSjVSSJHm+1umZ6tKByvsaMJ
    jl4iBZCT+X3RM15xZSYikHpIYwFBtSjv3mDQuNu51Hyj5dOl8cpxJNQoukbG3S4p
    bAIziKap+m2xAXACFKByPWXzuYA/PuSk2kvgEkT2Ib/+bb8ZsKv4eL07qHHTrnN9
    eNGvnrOmS3etUKPq12fozY0W/Af4/GWIaYadJqFklEA8UBlurwv53wou6j2DwdY7
    Z1cTM0Y05kAz/eRq1a8rjQWENrPwoo13o2EmUoUSLfENOQgZKIvboK3WjylSJc57
    k0bBqqrQ+4ehsoAEktImsLxu8HgxNL9Qs+wWOqpvdhq9vpLcJFyt69JF1x4+f3UZ
    GEIHQsbV4mNWcAQVNaiBlUILFWg8f5uAlzDqnhLMkQJToeaQApJQzCd/6BxZcf85
    y8z3IK1qbOMaN0jcra5AcJ5PorHH2Lk5+vdObeNM4S8F03CSmUDG6+sltoQpCcKi
    /gktDjhOx3hmU6HD6AskZXspKgZjgRw6MVZMkRw7gqLlxY2DVPJK/kuegJH1/OEd
    ObR7pGUiNpSxst8MyvXvWZx6LgjrRGRASbaQi04bLNPm4Dx80VZ/hPzdP0xw6QtT
    YxQ3ZCu1jTH38Q0UVLXa5KJ1dfUGpTUXUJycjV65cCVDRArTsGpU1BVozbwwc2Ud
    GUbM2pY1pStzOb2mbvr08uUCY/mdjkP4Ij/GTlpcbu3erHOr/0R8peedNEQEggPo
    YNg0TiWFw9iVTItRuqVD8GfiO0grCKF/yCQ/Y4HN5j9BIyExvmqZtVlB6APYaIPj
    3eoC3CYpFyTRQCoiubzK9rvpjNPn0hUGAAupJ9IyaNn+OPK1+2x3g0xtahq9ZDLN
    ainO0kQ7JGky4kQgRM0kQNE71l1nhImiLs6hvVUEgknJi+B3sZyXuI186hBQZ9lT
    3TLRi1EUBBDJgopkwVMP63BUv8qxt3T0YU9GAYVyte0OdDc2b89Tvu3ZfIHhhLA5
    T5ZVOUHFQiPBv990t0w6jgr97tTE8SyJlS2+Ybz8KMpiDoZaNVkJx4EqiZ/Vlc+I
    tc98JAp9wal0Nh7+m3jWVnm8ryxgYVDsv7p7Ai96SRXClHf6H3adw9Svk4StNAZc
    vpwm8jApBIID6Mjlvts8dU6NBtLgrBqmMaiLNG4GDVu+0pwHmblQB5QNX2qiiyjt
    UsAHuek/xS3VRyqOTkZYTfx2SGMe6pJlonQ2HgEjye39hNLEQqfCSd94vhM+M2ex
    yC4SMbXpEP+RFeoOfxanSNkl8CQmCqzUD8E5s0WFyocgsO5un3jXaJ7D4IAI5Ge9
    4PT7vx7yuZC3DFwQNdJpcbHrC3rBhdYqPmcUSkNWwIYuXTmaSp+S7iaCTkasYu0H
    91KqVZHgWkK3mZ+gwxZDdlsLxXEeVNanNeEvkDdV8sNuvhhG866taOK6Bi+GHqRG
    0cVWPM4qVp6r6Tqb1TAfyIwaL5tYeKRsam/3EzTz4dAx9RPq3P3B6JlDM0lDDwSr
    GIEA9u/efiompVryLmN8lFwY12/3CGO4u3JRUtGP2xSTeoaA5nyNk2lLTH9grA9Z
    WndkGFhNJdWJHgog29uMmIJPcJHoexeCTqgj3hLD7vUA2qx17+ybRjD2cx3rC7wG
    obm+6jHA55NgAKHME6bmrPlPf9kpVWmuzrYE6ovPxSrlkrhIMxOmMA2qElBSm0av
    9zq6HtwSuhbFuN14Fysm8l9w6Km4x6CtAQs9SnTQ3lPpCJGNCWZoI4CW2E13Hz1s
    EhBybjlqiMYrkGul4LD+QtZXj7nXYFX0NQ0PjIbdX5GB0mlIgsGSeet9f8+fLBid
    Lf6kexMRitvlw/S7x9L7EWIluYGI3WWUQBpF6l7fkKw260HR0G9XVF/06Oxbl66m
    FQSY/k1Fo+wh0v8QZnAL2Nd9MsBKV0izU3rqF8qyjDw3FdAn/d7on+HhNNVf5VPl
    mGQkWoGK1BUK1Yh+m0AWqCocMbWvw3B/RW1A0OFrk7FPZ+bzLVpX96wmXs5xMvu9
    ekr6L/lK4fCrmhuIAd2lLCTlYVYOUjdMHb9J5H4umXm1jqsStGwaEaRtiqoEggPo
    X5QDBrKZuxO0EbDIZL0ZjbkFwY252z7/3hj/8m70jDMgaBjFn0sE/RvFIRbI5t+d
    ZNUn37t4EBiyTDx9ZsDUsz7il+5b3Ca/5bCzURi5SxcK5zHxi9570Ep4igwqCHCB
    zdhrYOggt6YKksMfpdE9JhG+YYEJbR4TOXrJ1YW5zHBEMowfqdVel7W4x0Wfnt3Z
    Ulb6iRzO+K0wv1c/VBnCz5C5ofkVCxcL8Jl0a4Eq4iW3MYtYm7QssAgm+tc8HLJ6
    UgfFVCzDlekcbVHnX1hIrUSIw9hAEyHbBm1N9WLjHJqiGRbLEYAPN27a7blFZFkS
    g3FI/NOOOwaVsodxgaY1LQrfuDKjwA476br+/ONR48CaoKKRd1Eh5RlmE9LSSzSU
    1QIEggPowO1J0O9Ob3iX6Ab5udssAXiWv1F1pe/oFIL+5yBfve8PvUM3FPNr7Ava
    U3+QyXpJUXK1BrCeYXWXTIY6mWjSMEnmZD0U2m/Nufm450YTz4ntJdxLNt5BsigP
    nZKmmUJT677FDOm4wgBMifqiRhWn4GcbJOp/Y5bU1Xkroq/n5cvnpdsaQpBU9Vmt
    UhP2KQv8tCRJtBk7jpHEyS8PuuRLnK3T751lhYkNatfnb7swb4fP8LS9pSKEH9bN
    LelxWP3HMDOR5w2ykh6E323bnVyRrlaoo5L6/ghvKuEhF4eMkOWNxBCacM7O2LHH
    cPWgPUksuiw4nhiNWb3JxOi5wrboRjS9YKVLPOm3VuMmVCInNbjEzS/NzBj8Uhk+
    W7mY8Fz/xdDAHyxaKbKhxlFL399rFKL46dDR2GTKTiC1CoPhzWRz+Ny5r0a3gjAF
    0NF2FeuDRcZaDKAnf17VTHknv+FucfiWd75BtAvHVToWm3kOes1ZEt7IBGIDf0eM
    Vhlfh0b1V/UdMq3kCSd6TMqNGufjlPfubmybUUs2A6auYamon6HihKFmAAk+tfpW
    Rwp62aJ53AF07QP3WtDovQ8o1VdaGJt0+QoUJXbmGRL/0DhL/6nlCCqei8HKrGkw
    SJnz6LfKnpth2P4wrA9/twb7sYiluH7bjSU7GQLUkKWWkSaIiuqQkaaSJuQhWmIp
    V9Gs0AC5FdbpFjtSDCBuLM+KlPEohcaVcPkDn7QtfI1tlGeyWcG/mXMbFGIlJ6dV
    zooEQVYQNe9Doqa6vCkQSTO5DlGccD0E1Ou99hoDOqCihyLjZSaL7N+AZ1HOYH1t
    li2Kr0YK5+5i+T4Djp2PixNa6sMNHVcm5SCP4ha2xhc0j9btUyGBHZ48ZG8NHu9K
    unIzmecr0Bw0JAsYfEBGu3l8ywAsQ4WMo09z8xG9/52altdK85BKB//9pEMEggPo
    BvoSggclEoWkdyHJ9mY+8JtQsMlUkm94y8dQG1jKubqijvyi0pRY21fAIwcZOoyj
    YFcgqwVrNpnbmIwS8+UZ4tajryFnRNGbzeUqD5aWP+6CVGZtrgaDXVLH0TGuR7Oi
    NtzYJ81mat4FINKZkXO72Wjev0cxlfbtQYvKC7JEa2TVFHAf5jP0YM+PWX0bcLge
    +18o9mZKmK10rI7VmxQjszE+dMpjrVDpthaFGJnxSlPxY4rptB3GSlaRYzIS11sM
    q3+VJSf39zNOSZTOUm+TllmC95pbNjdLxQXOndIccPc8A5q8sLbWMz8IjnKXz2BH
    4x6BS1jzYpnafGduLRa9dHnXWGCA3m3E4hLQbd7iMSXGo+wxFeDlVvSFN0fCiwSC
    A+hvsbu0qHmCPI0gnfIOF5IJmFIzGoCqYJmB6m6+opGP5Rw/WVwkwsQpIj9U65ID
    /o65VW+WvpEvIMNW7yXr2DkAuDc5EH9Ehkif62h4cRFUUGSggy22YsVUsAw6/anm
    uR/SeL2JBqNtJq93SBLpintMQGFYnZUyehop1xgXsQf+0FIMbq0zqfh64SK4Mu9H
    dZCvvKWMZyKK8GnGHdmOhSBpG7WoPamJ6RnRezjoGZvDHfQ5z5O0m0KfZuvv8VhO
    WOHqRY2kwUWYZf8DpECBmbf1ss1bSrkOaE6is3eAkRAoqoRjw+hVRaLanburaIbX
    jyenX5rWXhcETpSAgU/FCX9OXo9rreJY7YID2wQW1W5BkUoJlaUHPwq22hTRO/og
    syd+aJh1HNES+lumBrjwsdQ1FMmksdfn6dT0YY14rHUrkU95hal8j28HbU71XY7K
    oOH65mUbV4jp4JPE1OQLCnECOsGT7ox+5yUQwAk+W7tVG2ita0LmDwWfhxws6jcu
    UskhNK0iESpasKL38vRkhvvF65wuM6BIPmBDu4pEsEyeW9O35SJ5hSm8IQRspZWq
    ClGQ2jCTGF4diYu4Z/rxEtBodLXJKmXqH52ZPVXLP2EyFZca4IDAMJK5i9TDpkjA
    2UJCi+4UO5s59GRk76ZKyAW4rz6BhgOa68he1zLxIhYr1zxzByXvKmj4Fiogdfp6
    ZltQ07/0eQ6RMwjSWnhBYhXOV2Wbpr4p0XR0VkDUGETSdJS6a9/iSiaEa16Yr+fb
    bOdrmpoMXh6JEFLsJJYbxMpORO9MTRGpPFmGOgsmUb7StvvjBAwgvsk0h8q20SdY
    zKlTkqTlalM6ACBJkofYVkOIxeIRLJhu0QmPjBMu34V15EP9iRlECV57dzWdmkbv
    h4sRnd46OhAOm86kda9hhEXrn/RzPD/eGis42v8VTi11xZ38tkqCCAJGPDwEggLo
    5VmIUamYcekI2DLrFWaat4zIL3RaWPJl6j5CcO+15Iw+iSkk33E4v1H5WqwYHImj
    93PWZ6Krut9VurQYpqk5hLhPgUeDwVB/DwsG9pulDjgS4h7K0nlIlpjJpzzu2afX
    +f/dxiy97XgAsr3utlg+u0pAWgEyBcmmKDJ0wRNM1I+M4dcaH4maD5tY87PNTnyn
    XtR6j2XIunTELl2WrFisURIVPN40Fj8hAhnYClcTjA0FWP+USxA6c0MsbkX+t4Op
    siwuL9/6eJ7ur2zCs3ZbBXfgO1bRsRQrIAYyrR38YS1Zjzj/9UwXiKsIEE6D2nNa
    AohpyB+OPivmagYyfGnJczZwqe/N1LKB1k2qqgIXDfI+ZlCZ5U78u+4gBIIB2now
    l4ewUKbq6+TtISzcPesBbnyjcD7/RhMmaGRvO3Hc09T8Oa4s50rDp8Cat36b4ZHl
    QUYAiUV2TWe1ftoAgEpnuxGHnujfHJPsJLN8ILUEkL5KBQ+UFUt29yEDtUUn8OZm
    QCECc8qf8+AoGVkGFKTZ72md6OgRyDHo8N+RKg+wkGaFOC//Svi0hnERX+qyrzKx
    wPJFiGkWPkRdYnZy+ICo11/ggHVyNuwHZLXxxJTkuVRaRFQWyjdn+SU7+2VjQ8iB
    zaCmkLlPP3mhbaEaNw6ME83B2zAjpMQKZJT2LIDu/qp5SCLunHC97ksfxAUqVGS5
    0LiSNpaMmWjqrrTp2bsTZCinzMHeMeJBay3Q9PrYEwRSoZzgz+ipU+riILK6gSnO
    y1xwfIA3bbytziUsWcAp0ZyDiDZvomAquidwC03DHXnfuHaFdGjRoU/yj4HWAtWh
    28xmOPAEkMTmXh+qT+fOEBcZvDsJTVKV+mxsftQN439tGwFkd0JxyLgSJFJo1AN5
    qZhHI5YH6B9ea1iISDmTwDNaEjYL0JOxhNejpQdVpkRWw/2/gI9uw8Mz2PYi2GzB
    Ig6hHJHdH5FBDDGuy/K6LVjvmfSZZTc9P43kVwAAAAAAAAAAAAAAAAAAAAAAADA+
    MCEwCQYFKw4DAhoFAAQUITSnLWE01o9hPGqPI9qLj9nwxZIEFPetASiZteRo3JXf
    cyqcvZKTliL7AgMBkAAAAA==