bases:
- ../../../webapp

patchesStrategicMerge:
- deployment.yml
- ingress.yml
- cert-secret.yml
- ingress-route-tcp.yml

namespace: app-eshop

configMapGenerator:
- name: webapp-env
  behavior: merge
  literals:
    - IdentityUrl=https://identity-api.aks.carbon-aware-computing.com
    - Kestrel__Certificates__Default__Path=certs/web.pfx
    - Kestrel__Certificates__Default__Password=xx
    - ASPNETCORE_HTTP_PORTS=8080
    - ASPNETCORE_HTTPS_PORTS=8443

