resources:
- deployment.yml
- service.yml
- ingress.yml
- cert-secret.yml
- ingress-route-tcp.yml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- name: identity-api-env
  literals:
    - OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES=true
    - OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES=true
    - ConnectionStrings__identitydb=Host=postgres;Port=5432;Username=postgres;Password=NwkrqbHkIK;
    - BasketApiClient=http://basket-api:0
    - OrderingApiClient=http://ordering-api:0
    - WebhooksApiClient=http://webhooks-api:0
    - WebhooksWebClient=https://webhooksclient:0
    - WebAppClient=https://webapp:0
    - ASPNETCORE_FORWARDEDHEADERS_ENABLED=true
    - ASPNETCORE_HTTP_PORTS=8080    

