resources:
- deployment.yml
- service.yml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- name: catalog-api-env
  literals:
    - OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES=true
    - OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES=true
    - ConnectionStrings__eventbus=amqp://guest:PFV8aZQjil@eventbus:5672
    - ConnectionStrings__catalogdb=Host=postgres;Port=5432;Username=postgres;Password=NwkrqbHkIK;
    - ASPNETCORE_FORWARDEDHEADERS_ENABLED=true
    - ASPNETCORE_URLS=http://+:8080

