---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: eventbus
spec:
  minReadySeconds: 60
  replicas: 1
  selector:
    matchLabels:
      app: eventbus
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: eventbus
    spec:
      containers:
      - name: eventbus
        image: rabbitmq:3
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5672
        envFrom:
        - configMapRef:
            name: eventbus-env
      terminationGracePeriodSeconds: 180