environments:
  default:
    values:
      - ./environments/values.yaml
      - ./environments/secrets.yaml

---
{{ $local := "./charts" }}
templates:
  default: &default
    missingFileHandler: Debug
    valuesTemplate:
      - './values/{{ "{{" }} splitList "/" .Release.Chart | last {{ "}}" }}.chart.yaml'
      - './values/{{ "{{" }} splitList "/" .Release.Chart | last {{ "}}" }}.chart.yaml.gotmpl'
      - './values/{{ "{{" }} .Release.Name {{ "}}" }}.yaml'
      - './values/{{ "{{" }} .Release.Name {{ "}}" }}.yaml.gotmpl'
      - './secrets/{{ "{{" }} splitList "/" .Release.Chart | last {{ "}}" }}.chart.yaml'
      - './secrets/{{ "{{" }} splitList "/" .Release.Chart | last {{ "}}" }}.chart.yaml.gotmpl'
      - './secrets/{{ "{{" }} .Release.Name {{ "}}" }}.yaml'
      - './secrets/{{ "{{" }} .Release.Name {{ "}}" }}.yaml.gotmpl'

repositories:
  - name: kepler
    url: https://sustainable-computing-io.github.io/kepler-helm-chart

  - name: prometheus-community
    url: https://prometheus-community.github.io/helm-charts

  - name: traefik
    url: https://helm.traefik.io/traefik/

  - name: kedacore
    url: https://kedacore.github.io/charts

  - name: bjw-s
    url: https://bjw-s.github.io/helm-charts/

  - name: fairwinds-stable
    url: https://charts.fairwinds.com/stable

  - name: k8s-as-helm
    url: https://ameijer.github.io/k8s-as-helm/

releases:
  - <<: *default
    name: traefik
    namespace: kube-system
    chart: traefik/traefik
    version: ^27.0.2


  - <<: *default
    name: kepler
    namespace: monitoring
    chart: kepler/kepler
    version: '0.5.5'

  - <<: *default
    name: kube-prometheus-stack
    namespace: monitoring
    chart: prometheus-community/kube-prometheus-stack
    version: ^57.1.0

  - <<: *default
    name: dashboards
    namespace: monitoring
    chart: {{ $local }}/resource

  - <<: *default
    name: keda
    namespace: scaling
    chart: kedacore/keda
    version: ^2.13.2

  # TODO: Chart is currently static. Needs to be made more dynamic.
  - <<: *default
    name: carbon-aware-keda-operator
    namespace: scaling
    chart: {{ $local }}/carbon-aware-keda-operator

  - <<: *default
    name: goldilocks
    namespace: scaling
    chart: fairwinds-stable/goldilocks
    version: ^8.0.1

  - <<: *default
    name: grid-carbon-intensity-configmap-exporter
    namespace: scaling
    chart: bjw-s/app-template
    version: ^3.0.4

  - <<: *default
    name: grid-carbon-intensity-configmap-exporter-crb
    # namespace: scaling
    chart: k8s-as-helm/clusterrolebinding
    version: ^1.0.0

  - <<: *default
    name: whoami
    namespace: app-testing
    chart: bjw-s/app-template
    version: ^3.0.4

  - <<: *default
    name: whoami-autoscaling
    namespace: app-testing
    chart: {{ $local }}/resource

  - <<: *default
    name: whoami-carbon-aware-scaling
    namespace: app-testing
    chart: {{ $local }}/resource
