environments:
  default:
    values:
      - ./environments/values.yaml
      - ./environments/secrets.yaml

---

templates:
  default: &default
    missingFileHandler: Debug
    valuesTemplate:
      - './values/{{ "{{" }} splitList "/" .Release.Chart | last {{ "}}" }}.chart.yaml'
      - './values/{{ "{{" }} splitList "/" .Release.Chart | last {{ "}}" }}.chart.yaml.gotmpl'
      - './values/{{ "{{" }} .Release.Name {{ "}}" }}.yaml'
      - './values/{{ "{{" }} .Release.Name {{ "}}" }}.yaml.gotmpl'
      - './secrets/{{ "{{" }} splitList "/" .Release.Chart | last {{ "}}" }}.chart.yaml'
      - './secrets/{{ "{{" }} splitList "/" .Release.Chart | last {{ "}}" }}.chart.yaml.gotmpl'
      - './secrets/{{ "{{" }} .Release.Name {{ "}}" }}.yaml'
      - './secrets/{{ "{{" }} .Release.Name {{ "}}" }}.yaml.gotmpl'

repositories:
  - name: kepler
    url: https://sustainable-computing-io.github.io/kepler-helm-chart

  - name: prometheus-community
    url: https://prometheus-community.github.io/helm-charts

  - name: traefik
    url: https://helm.traefik.io/traefik/

  - name: kedacore
    url: https://kedacore.github.io/charts

releases:
  - <<: *default
    name: kepler
    namespace: monitoring
    chart: kepler/kepler
    version: '0.5.5'

  - <<: *default
    name: kube-prometheus-stack
    namespace: monitoring
    chart: prometheus-community/kube-prometheus-stack
    version: ^57.1.0

  - <<: *default
    name: traefik
    namespace: kube-system
    chart: traefik/traefik
    version: ^26.1.0

  - <<: *default
    name: keda
    namespace: scaling
    chart: kedacore/keda
    version: ^2.13.2
