environments:
  default:
    values:
      - ./environments/default.yaml

---

templates:
  default: &default
    missingFileHandler: Debug
    valuesTemplate:
      - './values/{{ "{{" }} splitList "/" .Release.Chart | last {{ "}}" }}.chart.yaml'
      - './values/{{ "{{" }} splitList "/" .Release.Chart | last {{ "}}" }}.chart.yaml.gotmpl'
      - './values/{{ "{{" }} .Release.Name {{ "}}" }}.yaml'
      - './values/{{ "{{" }} .Release.Name {{ "}}" }}.yaml.gotmpl'
    secrets:
      - './secrets/{{ "{{" }} splitList "/" .Release.Chart | last {{ "}}" }}.chart.yaml'
      - './secrets/{{ "{{" }} splitList "/" .Release.Chart | last {{ "}}" }}.chart.yaml.gotmpl'
      - './secrets/{{ "{{" }} .Release.Name {{ "}}" }}.yaml'
      - './secrets/{{ "{{" }} .Release.Name {{ "}}" }}.yaml.gotmpl'

repositories:
  - name: azuredisk-csi-driver
    url: https://raw.githubusercontent.com/kubernetes-sigs/azuredisk-csi-driver/master/charts

releases:
  - <<: *default
    name: azuredisk-csi-driver
    namespace: kube-system
    chart: azuredisk-csi-driver/azuredisk-csi-driver
    version: ^1.30.0
