environments:
  default:
    values:
      - ./environments/default.yaml

---

templates:
  default: &default
    missingFileHandler: Debug
    valuesTemplate:
      - './values/{{ "{{" }} splitList "/" .Release.Chart | last {{ "}}" }}.chart.yaml'
      - './values/{{ "{{" }} splitList "/" .Release.Chart | last {{ "}}" }}.chart.yaml.gotmpl'
      - './values/{{ "{{" }} .Release.Name {{ "}}" }}.yaml'
      - './values/{{ "{{" }} .Release.Name {{ "}}" }}.yaml.gotmpl'
      - './secrets/{{ "{{" }} splitList "/" .Release.Chart | last {{ "}}" }}.chart.yaml'
      - './secrets/{{ "{{" }} splitList "/" .Release.Chart | last {{ "}}" }}.chart.yaml.gotmpl'
      - './secrets/{{ "{{" }} .Release.Name {{ "}}" }}.yaml'
      - './secrets/{{ "{{" }} .Release.Name {{ "}}" }}.yaml.gotmpl'

repositories:
  - name: kepler
    url: https://sustainable-computing-io.github.io/kepler-helm-chart

releases:
  - <<: *default
    name: kepler
    namespace: monitoring
    chart: kepler/kepler
    version: '0.5.5'
