{{ readFile "./_base.helmfile.yaml" }}
{{ $local := "./charts" }}

repositories:
  - name: fairwinds-stable
    url: https://charts.fairwinds.com/stable

releases:
  - <<: *default
    name: goldilocks
    namespace: scaling
    chart: fairwinds-stable/goldilocks
    version: ^8.0.1
